# lightning==2.3.0.dev0
seed_everything: 0
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 40
  use_distributed_sampler: false
  limit_train_batches: 100
  log_every_n_steps: 1
  default_root_dir: ./results
model:
  forecaster:
    class_path: probts.model.forecaster.prob_forecaster.LagLlama
    init_args:
      use_rope_scaling: true
      ckpt_path: ./checkpoints/lag-llama/lag-llama.ckpt
  num_samples: 100
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: solar_nips
      split_val: true
      scaler: identity # identity, standard, temporal
      timeenc: 2
  batch_size: 1
  test_batch_size: 1
  num_workers: 8