# lightning==2.3.0.dev0
seed_everything: 0
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 40
  use_distributed_sampler: false
  limit_train_batches: 100
  log_every_n_steps: 1
  default_root_dir: ./results
model:
  forecaster:
    class_path: probts.model.forecaster.point_forecaster.TimesFM
    init_args:
        input_patch_len: 32
        output_patch_len: 128
        num_layers: 20
        model_dims: 1280
  quantiles_num: 20
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: solar_nips
      split_val: true
      scaler: identity # identity, standard, temporal
      var_specific_norm: true
  batch_size: 64
  test_batch_size: 64
  num_workers: 8