# lightning==2.3.0.dev0
seed_everything: 1
trainer:
  accelerator: gpu
  devices: 1
  strategy: auto
  max_epochs: 30
  use_distributed_sampler: false
  limit_train_batches: 100
  log_every_n_steps: 1
  default_root_dir: ./results
model:
  forecaster:
    class_path: probts.model.forecaster.point_forecaster.LinearForecaster
    init_args:
      individual: false
      use_lags: true
  learning_rate: 0.001
  quantiles_num: 20
  num_samples: 100
data:
  data_manager:
    class_path: probts.data.data_manager.DataManager
    init_args:
      dataset: ettm2
      split_val: true
      scaler: standard # identity, standard, temporal
      context_length: 24
      prediction_length: 24
  batch_size: 64
  test_batch_size: 64
  num_workers: 8
